# Generated by Django 5.2.7 on 2025-10-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_alter_car_manufacturer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
            },
        ),
    ]
